# Generated by Django 4.2.2 on 2023-06-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nicname",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
