# Generated by Django 4.2.2 on 2023-07-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mon", models.CharField(max_length=50)),
                ("tue", models.CharField(max_length=50)),
                ("wed", models.CharField(max_length=50)),
                ("thu", models.CharField(max_length=50)),
                ("fri", models.CharField(max_length=50)),
                ("sat", models.CharField(max_length=50)),
                ("sun", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "city",
                    models.CharField(
                        choices=[("서울", "서울"), ("인천", "인천"), ("부산", "부산")],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("img", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="cafes.cafe",
                    ),
                ),
            ],
        ),
    ]
