# Generated by Django 4.2.2 on 2023-07-06 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("filters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="business_hours",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="cafes.businesshours"
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="filters.city"
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="reviews",
            field=models.ManyToManyField(
                through="cafes.Review", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
