# Generated by Django 4.2.2 on 2023-06-22 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="like",
            field=models.ManyToManyField(
                related_name="like_cafes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
