# Generated by Django 4.2.2 on 2023-07-09 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filters", "0006_city_option_filter_option"),
        ("cafes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="filters.city"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(2)]
            ),
        ),
    ]
