# Generated by Django 4.2.2 on 2023-06-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
