# Generated by Django 4.2.2 on 2023-06-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fillers", "0001_initial"),
        ("cafes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="filler",
            field=models.ManyToManyField(
                related_name="filler_reviews", to="fillers.filler"
            ),
        ),
    ]
