# Generated by Django 4.2.2 on 2023-06-27 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cafes", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="reviews",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="cafe",
            name="options",
        ),
        migrations.RemoveField(
            model_name="cafe",
            name="reviews",
        ),
        migrations.AlterField(
            model_name="cafe",
            name="city",
            field=models.CharField(
                choices=[("서울", "서울"), ("인천", "인천"), ("부산", "부산")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="cafe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="cafes.cafe",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
