# Generated by Django 4.2.2 on 2023-06-29 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafes", "0003_rename_reviews_review_content_remove_cafe_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cafe",
            name="map",
        ),
    ]
