# Generated by Django 4.2.2 on 2023-07-03 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("filters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotbox",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="ballot_boxs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
