# Generated by Django 4.2.2 on 2023-06-27 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cafes", "0003_rename_reviews_review_content_remove_cafe_options_and_more"),
        ("filters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BallotBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballot_boxs",
                        to="cafes.cafe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilterScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="option",
            name="filter",
        ),
        migrations.RemoveField(
            model_name="filter",
            name="city",
        ),
        migrations.AddField(
            model_name="filter",
            name="img",
            field=models.URLField(default=343),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filter",
            name="option",
            field=models.CharField(
                choices=[
                    ("productivity", "Productivity"),
                    ("community", "Community"),
                    ("service", "Service"),
                ],
                default="wifi",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.AddField(
            model_name="ballotbox",
            name="filter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballot_boxs",
                to="filters.filter",
            ),
        ),
        migrations.AddField(
            model_name="ballotbox",
            name="score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballot_boxs",
                to="filters.filterscore",
            ),
        ),
        migrations.AddField(
            model_name="ballotbox",
            name="users",
            field=models.ManyToManyField(
                related_name="ballot_boxs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
