# Generated by Django 4.2.2 on 2023-06-29 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("filters", "0002_ballotbox_filterscore_remove_option_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballotbox",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="ballot_boxs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
