# Generated by Django 4.2.2 on 2023-07-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filters", "0003_remove_filter_img_remove_filter_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
