# Generated by Django 4.2.2 on 2023-07-04 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filters", "0004_alter_filter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterscore",
            name="score",
            field=models.PositiveIntegerField(
                unique=True, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
