# Generated by Django 4.2.2 on 2023-06-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="filler",
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(),
        ),
    ]
